services:
  chromedriver:
    image: selenium/standalone-chrome:latest
    container_name: chromedriver
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4444/wd/hub/status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: on-failure