[pytest]
# Отключить все warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::FutureWarning
    ignore::UserWarning

# Или можно использовать более простой вариант:
# addopts = --disable-warnings

# Настройки вывода
addopts = -v --tb=short --disable-warnings

# Путь к тестам
testpaths = .
python_files = test*.py
python_classes = *Test
python_functions = test_*
